CC=gcc
CFLAGS=-I../../lib -D WIN32
LDFLAGS=

EXECUTABLE=sh_file

SOURCES= main.c \
../../lib/c_cache.c \
../../lib/c_sh.c \
../../lib/nprintf.c

OBJECTS=$(notdir $(SOURCES:%.c=%.o))

all:  test

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) -o $(EXECUTABLE)

%.o: ../../lib/%.c
	$(CC) -c $(CFLAGS) -o $@ $<

clean:
	rm $(EXECUTABLE) $(OBJECTS)

test: $(EXECUTABLE)
	./$(EXECUTABLE) all_test.sh

