CC=i686-w64-mingw32-gcc
CFLAGS=-I../../lib -D WIN_CONSOLE -D WIN32
LDFLAGS=

EXECUTABLE=shell.exe

SOURCES= ../shell/main.c \
../shell/test_shell.c \
../../lib/loop_buff.c \
../../lib/c_tty.c \
../../lib/c_cache.c \
../../lib/c_sh.c \
../../lib/c_sh_embed.c \
../../lib/c_sh_pars.c \
../../lib/nprintf.c

OBJECTS=$(notdir $(SOURCES:%.c=%.o))

all:  test

ifeq ($(OS),Windows_NT)
    #Windows stuff
    WINE = cmd /c
else
    #Linux stuff
    WINE = wine
endif

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) -o $(EXECUTABLE)

%.o: ../../lib/%.c
	$(CC) -c $(CFLAGS) -o $@ $<

%.o: ../shell/%.c
	$(CC) -c $(CFLAGS) -o $@ $<

clean:
	rm $(EXECUTABLE) $(OBJECTS)

test: $(EXECUTABLE)
	$(WINE) $(EXECUTABLE) all_test.sh

